server:
    port: 9090
app:
    name: tdbada
    description: Projet bdd NoSql BADA by Achraf the big boss and FUTUR CADRE

couch:
    url: http://localhost:5984/meulun/

mongo:
    url: http://localhost:8100/


neo4j:
    url: llll

cassandra:
    url: kkkk

redis:
    url: redis

firebase:
    url: llooj

projetvoldemort:
    url: lllok
