server:
    port: 9090
app:
    name: tdbada
    description: Projet bdd NoSql BADA

couchdb:
    url: http://localhost:9100/

mongo:
    url: http://localhost:8100/


neo4j:
    url: llll

cassandra:
    url: kkkk

redis:
    url: redis

firebase:
    url: llooj

projetvoldemort:
    url: lllok
