package com.bada.model.utils;

public class UNE_PONDERATION {

    private String  PONDERATION_TYPE;
    private String  PONDERATION_STATUTAIRE;
    private String  PONDERATION_SUPPLEMENTAIRE;

    public UNE_PONDERATION() {
    }

    public UNE_PONDERATION(String PONDERATION_TYPE, String PONDERATION_STATUTAIRE, String PONDERATION_SUPPLEMENTAIRE) {
        this.PONDERATION_TYPE = PONDERATION_TYPE;
        this.PONDERATION_STATUTAIRE = PONDERATION_STATUTAIRE;
        this.PONDERATION_SUPPLEMENTAIRE = PONDERATION_SUPPLEMENTAIRE;
    }

    public String getPONDERATION_TYPE() {
        return PONDERATION_TYPE;
    }

    public void setPONDERATION_TYPE(String PONDERATION_TYPE) {
        this.PONDERATION_TYPE = PONDERATION_TYPE;
    }

    public String getPONDERATION_STATUTAIRE() {
        return PONDERATION_STATUTAIRE;
    }

    public void setPONDERATION_STATUTAIRE(String PONDERATION_STATUTAIRE) {
        this.PONDERATION_STATUTAIRE = PONDERATION_STATUTAIRE;
    }

    public String getPONDERATION_SUPPLEMENTAIRE() {
        return PONDERATION_SUPPLEMENTAIRE;
    }

    public void setPONDERATION_SUPPLEMENTAIRE(String PONDERATION_SUPPLEMENTAIRE) {
        this.PONDERATION_SUPPLEMENTAIRE = PONDERATION_SUPPLEMENTAIRE;
    }
}
